version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    volumes:
    # 容器启动后会自动调用下述文件夹中的 shell/sql 脚本，可用于自动化建库建表。
    - create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    # 保存 mysql 数据
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      # 也可以创建自定义的管理员账号密码
      # MYSQL_USER: change_me
      # MYSQL_PASSWORD: change_me

      # 如果只需要用到一个数据库，可直接使用环境这个变量创建
      # MYSQL_DATABASE: mydb